
# VALID BOOK REQUESTS

### route
GET http://localhost:4000 HTTP/1.1

### List all books
GET http://localhost:4000/api/books HTTP/1.1


### List all books filtered by genre
GET http://localhost:4000/api/books?genre=action&isRead=false HTTP/1.1

### List all books filtered by isRead-status
GET http://localhost:4000/api/books?isRead=false HTTP/1.1


### Create a new book
POST http://localhost:4000/api/books HTTP/1.1
Content-Type: application/json

[
  {
    "title": "The Ringworld Engineers",
    "author": "Larry Niven",
    "genre": "scifi",
    "isRead": true
  },
  {
    "title": "The Ringworld Throne",
    "author": "Larry Niven",
    "genre": "scifi",
    "isRead": true
  },
  {
    "title": "Ringworld's Children",
    "author": "Larry Niven",
    "genre": "scifi",
    "isRead": true
  },
  {
    "title": "The Colour of Magic",
    "author": "Terry Pratchett",
    "genre": "fantasy",
    "isRead": false
  },
  {
    "title": "Mort",
    "author": "Terry Pratchett",
    "genre": "fantasy",
    "isRead": false
  },
  {
    "title": "Guards! Guards!",
    "author": "Terry Pratchett",
    "genre": "fantasy",
    "isRead": false
  },
  {
    "title": "Moving Pictures",
    "author": "Terry Pratchett",
    "genre": "fantasy",
    "isRead": false
  },
  {
    "title": "Night Watch",
    "author": "Terry Pratchett",
    "genre": "fantasy",
    "isRead": false
  },
  {
    "title": "Daemon",
    "author": "Daniel Suarez",
    "genre": "techno thriller",
    "isRead": false
  },
  {
    "title": "Freedom",
    "author": "Daniel Suarez",
    "genre": "techno thriller",
    "isRead": false
  },
  {
    "title": "Kill Decision",
    "author": "Daniel Suarez",
    "genre": "techno thriller",
    "isRead": false
  },
  {
    "title": "Change Agent",
    "author": "Daniel Suarez",
    "genre": "techno thriller",
    "isRead": false
  }

]


### PATCH book by id (with existing id) (ie. update)
PATCH http://localhost:4000/api/books/6103d1ca783a5b23d7016f68 HTTP/1.1
Content-Type: application/json

{
  "isRead": true
}

### DELETE a book by id
DELETE  http://localhost:4000/api/books/6103da28ffe84d2c7cc1172f HTTP/1.1



# INVALID BOOK REQUESTS


### Create a new book  (inavlid input - maxlength exceeded)
POST http://localhost:4000/api/books HTTP/1.1
Content-Type: application/json

{
  "title": "In ut qui anim ad amet enim nisi elit est irure nisi incididunt. Dolor cillum laboris culpa irure reprehenderit. Duis labore minim eiusmod aute. Dolor aliquip eiusmod ex duis esse mollit. Mollit esse est sunt duis eu labore amet do ipsum quis.",
  "author": "Himnz"
}


### Create a new book  (inavlid input - no title povided)
POST http://localhost:4000/api/books HTTP/1.1
Content-Type: application/json

{
  "author": "Hinz"
}